version: "2"
run:
  concurrency: 10
linters:
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - goprintffuncname
    - gosmopolitan
    - govet
    - iface
    - ineffassign
    - misspell
    - modernize
    - musttag
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/extensions/errors/errors\.go$
      - internal/extensions/lexer/
      - internal/extensions/parser/action\.go$
      - internal/extensions/parser/actiontable\.go$
      - internal/extensions/parser/context\.go$
      - internal/extensions/parser/gototable\.go$
      - internal/extensions/parser/parser\.go$
      - internal/extensions/parser/productionstable\.go$
      - internal/extensions/token/
      - internal/extensions/util/
  settings:
    goconst:
      ignore-tests: true
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/extensions/errors/errors\.go$
      - internal/extensions/lexer/
      - internal/extensions/parser/action\.go$
      - internal/extensions/parser/actiontable\.go$
      - internal/extensions/parser/context\.go$
      - internal/extensions/parser/gototable\.go$
      - internal/extensions/parser/parser\.go$
      - internal/extensions/parser/productionstable\.go$
      - internal/extensions/token/
      - internal/extensions/util/
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(github.com/paulourio/gsql)
