package sql

// Code generated by helper.go. DO NOT EDIT.

type SkipTargetType int32

const (
	UnspecifiedSkipTarget SkipTargetType = 1
	PastLastRow SkipTargetType = 2
	ToNextRow SkipTargetType = 3
)

type IndexType int32

const (
	IndexDefaultIndex IndexType = 1
	SearchIndex IndexType = 2
	IndexVector IndexType = 3
)

type AnySomeAllOpType int32

const (
	UninitializedOp AnySomeAllOpType = 2
	AnyOp AnySomeAllOpType = 3
	SomeOp AnySomeAllOpType = 4
	AllOp AnySomeAllOpType = 5
)

type InsertionMode int32

const (
	NotSetInsertionMode InsertionMode = 1
	Append InsertionMode = 2
	Overwrite InsertionMode = 3
)

type BinaryOp int32

const (
	NotSetBinaryOp BinaryOp = 1
	LikeOp BinaryOp = 2
	IsOp BinaryOp = 3
	EqOp BinaryOp = 4
	NeOp BinaryOp = 5
	Ne2Op BinaryOp = 6
	GtOp BinaryOp = 7
	LtOp BinaryOp = 8
	GeOp BinaryOp = 9
	LeOp BinaryOp = 10
	BitwiseOrOp BinaryOp = 11
	BitwiseXorOp BinaryOp = 12
	BitwiseAndOp BinaryOp = 13
	PlusBinaryOp BinaryOp = 14
	MinusBinaryOp BinaryOp = 15
	MultiplyOp BinaryOp = 16
	DivideOp BinaryOp = 17
	ConcatOpOp BinaryOp = 18
	DistinctOp BinaryOp = 19
	IsSourceNodeOp BinaryOp = 20
	IsDestNodeOp BinaryOp = 21
)

type LhsOp int32

const (
	UpdateSingle LhsOp = 1
	UpdateManyLhsOp LhsOp = 2
	UpdateSingleNoCreation LhsOp = 3
)

type BreakContinueKeyword int32

const (
	BreakKeyword BreakContinueKeyword = 2
	LeaveKeyword BreakContinueKeyword = 3
	ContinueKeyword BreakContinueKeyword = 4
	IterateKeyword BreakContinueKeyword = 5
)

type RelativePosition int32

const (
	Preceding RelativePosition = 2
	Following RelativePosition = 3
)

type DeterminismLevel int32

const (
	UnspecifiedDeterminism DeterminismLevel = 1
	Deterministic DeterminismLevel = 2
	NotDeterministic DeterminismLevel = 3
	Immutable DeterminismLevel = 4
	Stable DeterminismLevel = 5
	Volatile DeterminismLevel = 6
)

type Scope int32

const (
	DefaultScope Scope = 1
	Private Scope = 2
	Public Scope = 3
	Temporary Scope = 4
)

type SqlSecurity int32

const (
	SqlSecurityUnspecifiedSecurity SqlSecurity = 1
	SqlSecurityDefiner SqlSecurity = 2
	SqlSecurityInvoker SqlSecurity = 3
)

type DropMode int32

const (
	DropModeUnspecifiedDropMode DropMode = 1
	RestrictDropMode DropMode = 2
	CascadeDropMode DropMode = 3
)

type SubqueryModifier int32

const (
	NoneModifier SubqueryModifier = 1
	Array SubqueryModifier = 2
	Exists SubqueryModifier = 3
	ValueSubqueryModifier SubqueryModifier = 4
)

type FilterType int32

const (
	NotSetFilterType FilterType = 1
	IncludeFilterType FilterType = 2
	ExcludeFilterType FilterType = 3
)

type ForeignKeyAction int32

const (
	NoAction ForeignKeyAction = 1
	RestrictAction ForeignKeyAction = 2
	CascadeAction ForeignKeyAction = 3
	SetNull ForeignKeyAction = 4
)

type ForeignKeyMatch int32

const (
	SimpleMatch ForeignKeyMatch = 2
	FullMatch ForeignKeyMatch = 3
	NotDistinct ForeignKeyMatch = 4
)

type NullHandlingModifier int32

const (
	DefaultNullHandling NullHandlingModifier = 1
	IgnoreNulls NullHandlingModifier = 2
	RespectNulls NullHandlingModifier = 3
)

type ParameterMode int32

const (
	NotSetParameterMode ParameterMode = 1
	InParameterMode ParameterMode = 2
	Out ParameterMode = 3
	Inout ParameterMode = 4
)

type GeneratedMode int32

const (
	Always GeneratedMode = 1
	ByDefaultMode GeneratedMode = 2
)

type StoredMode int32

const (
	NonStored StoredMode = 1
	Stored StoredMode = 2
	StoredVolatile StoredMode = 3
)

type EdgeOrientation int32

const (
	EdgeOrientationNotSetOrientation EdgeOrientation = 1
	AnyOrientation EdgeOrientation = 2
	LeftOrientation EdgeOrientation = 3
	RightOrientation EdgeOrientation = 4
)

type GraphLabelOp int32

const (
	GraphLabelOperationTypeUnspecified GraphLabelOp = 1
	NotGraphLabelOp GraphLabelOp = 2
	AndOp GraphLabelOp = 3
	OrOp GraphLabelOp = 4
)

type NodeReferenceType int32

const (
	NodeReferenceTypeUnspecifiedRefType NodeReferenceType = 1
	Source NodeReferenceType = 2
	Destination NodeReferenceType = 3
)

type PathMode int32

const (
	PathModeUnspecifiedPathMode PathMode = 1
	Walk PathMode = 2
	Trail PathMode = 3
	SimplePathMode PathMode = 4
	Acyclic PathMode = 5
)

type PathSearchPrefix int32

const (
	PathSearchPrefixTypeUnspecifiedPrefix PathSearchPrefix = 1
	AnyPrefix PathSearchPrefix = 2
	Shortest PathSearchPrefix = 3
	AllPrefix PathSearchPrefix = 4
	AllShortest PathSearchPrefix = 5
	Cheapest PathSearchPrefix = 6
	AllCheapest PathSearchPrefix = 7
)

type HavingModifierType int32

const (
	NotSetModifier HavingModifierType = 1
	Min HavingModifierType = 2
	Max HavingModifierType = 3
)

type ImportKind int32

const (
	Module ImportKind = 2
	Proto ImportKind = 3
)

type InsertMode int32

const (
	DefaultMode InsertMode = 1
	Replace InsertMode = 2
	UpdateInsertMode InsertMode = 3
	Ignore InsertMode = 4
)

type InsertParseProgress int32

const (
	Initial InsertParseProgress = 2
	SeenOrIgnoreReplaceUpdate InsertParseProgress = 3
	SeenTargetPath InsertParseProgress = 4
	SeenColumnList InsertParseProgress = 5
	SeenValuesList InsertParseProgress = 6
)

type JoinHint int32

const (
	NoJoinHint JoinHint = 1
	Hash JoinHint = 2
	Lookup JoinHint = 3
)

type JoinType int32

const (
	DefaultJoinType JoinType = 1
	Comma JoinType = 2
	Cross JoinType = 3
	FullJoin JoinType = 4
	InnerJoin JoinType = 5
	LeftJoin JoinType = 6
	RightJoin JoinType = 7
)

type LockStrength int32

const (
	NotSetLockStrength LockStrength = 1
	UpdateLockStrength LockStrength = 2
)

type MergeActionType int32

const (
	NotSetMergeAction MergeActionType = 1
	Insert MergeActionType = 2
	UpdateMergeAction MergeActionType = 3
	Delete MergeActionType = 4
)

type MergeMatchType int32

const (
	NotSetMatchType MergeMatchType = 1
	Matched MergeMatchType = 2
	NotMatchedBySource MergeMatchType = 3
	NotMatchedByTarget MergeMatchType = 4
)

type ConflictAction int32

const (
	NotSetConflictAction ConflictAction = 1
	Nothing ConflictAction = 2
	UpdateConflictAction ConflictAction = 3
)

type AssignmentOp int32

const (
	NotSetAssignmentOp AssignmentOp = 1
	AssignOp AssignmentOp = 2
	AddAssignOp AssignmentOp = 3
	SubAssignOp AssignmentOp = 4
)

type OrderingSpec int32

const (
	NotSetSpec OrderingSpec = 1
	Asc OrderingSpec = 2
	Desc OrderingSpec = 3
)

type RowPatternAnchorType int32

const (
	AnchorUnspecifiedAnchor RowPatternAnchorType = 1
	Start RowPatternAnchorType = 2
	End RowPatternAnchorType = 3
)

type RowPatternOp int32

const (
	RowPatternOperationTypeUnspecified RowPatternOp = 1
	ConcatOp RowPatternOp = 2
	AlternateOp RowPatternOp = 3
	PermuteOp RowPatternOp = 4
	ExcludeOp RowPatternOp = 5
)

type SampleSizeUnit int32

const (
	NotSetUnit SampleSizeUnit = 1
	RowsSampleSize SampleSizeUnit = 2
	Percent SampleSizeUnit = 3
)

type AsMode int32

const (
	NotSetAsMode AsMode = 1
	Struct AsMode = 2
	ValueAsMode AsMode = 3
	TypeName AsMode = 4
)

type AllOrDistinct int32

const (
	AllOrDistinctNotSetAllOrDistinct AllOrDistinct = 1
	AllSet AllOrDistinct = 2
	Distinct AllOrDistinct = 3
)

type ColumnMatchMode int32

const (
	ByPosition ColumnMatchMode = 2
	Corresponding ColumnMatchMode = 3
	CorrespondingBy ColumnMatchMode = 4
	ByName ColumnMatchMode = 5
	ByNameOn ColumnMatchMode = 6
)

type ColumnPropagationMode int32

const (
	Strict ColumnPropagationMode = 2
	InnerPropagation ColumnPropagationMode = 3
	LeftPropagation ColumnPropagationMode = 4
	FullPropagation ColumnPropagationMode = 5
)

type SetOp int32

const (
	NotSetSetOp SetOp = 1
	UnionOp SetOp = 2
	ExceptOp SetOp = 3
	IntersectOp SetOp = 5
)

type InterleaveClauseType int32

const (
	NotSetInterleaveType InterleaveClauseType = 1
	InInterleaveType InterleaveClauseType = 2
	InParent InterleaveClauseType = 3
)

type QuantifierSymbol int32

const (
	SymbolUnspecifiedSymbol QuantifierSymbol = 1
	QuestionMark QuantifierSymbol = 2
	Plus QuantifierSymbol = 3
	StarSymbol QuantifierSymbol = 4
)

type TemplatedTypeKind int32

const (
	UninitializedTypeKind TemplatedTypeKind = 2
	AnyType TemplatedTypeKind = 3
	AnyProto TemplatedTypeKind = 4
	AnyEnum TemplatedTypeKind = 5
	AnyStruct TemplatedTypeKind = 6
	AnyArray TemplatedTypeKind = 7
	AnyTable TemplatedTypeKind = 8
)

type ReadWriteMode int32

const (
	InvalidMode ReadWriteMode = 1
	ReadOnly ReadWriteMode = 2
	ReadWrite ReadWriteMode = 3
)

type UnaryOp int32

const (
	NotSetUnaryOp UnaryOp = 1
	NotUnaryOp UnaryOp = 2
	BitwiseNotOp UnaryOp = 3
	MinusUnaryOp UnaryOp = 4
	PlusUnaryOp UnaryOp = 5
	IsUnknownOp UnaryOp = 6
	IsNotUnknownOp UnaryOp = 7
)

type UnpivotNullFilter int32

const (
	UnspecifiedNullFilter UnpivotNullFilter = 2
	IncludeNullFilter UnpivotNullFilter = 3
	ExcludeNullFilter UnpivotNullFilter = 4
)

type FrameUnit int32

const (
	RowsFrameUnit FrameUnit = 2
	Range FrameUnit = 3
)

type BoundaryType int32

const (
	UnboundedPreceding BoundaryType = 2
	OffsetPreceding BoundaryType = 3
	CurrentRow BoundaryType = 4
	OffsetFollowing BoundaryType = 5
	UnboundedFollowing BoundaryType = 6
)

