[setup]
[setup.print_options]
soft_max_cols = 80
newline_before_clause = true
align_logical_with_clauses = false
column_list_trailing_comma = "NEVER"
indentation = 1
min_joins_to_separate_in_blocks = 2
function_name_style = "UPPER_CASE"
identifier_style = "AS_IS"
keyword_style = "UPPER_CASE"
type_style = "UPPER_CASE"
bool_style = "AS_IS"
null_style = "AS_IS"
bytes_style = "AS_IS"
string_style = "AS_IS"
hex_style = "UPPER_CASE"

[[cases]]
input = """
select x
|> drop a
|> drop a,
|> drop a,b,c
|> drop a,b,c,
"""
formatted = """
SELECT x
|> DROP a
|> DROP a
|> DROP a, b, c
|> DROP a, b, c
"""
