// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/paulourio/gsql/internal/extensions/token"
)

const (
	NoState    = -1
	NumStates  = 199
	NumSymbols = 183
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '-'
2: '\n'
3: '#'
4: '\n'
5: '/'
6: '/'
7: '\n'
8: '\n'
9: '{'
10: '%'
11: '-'
12: '-'
13: '%'
14: '}'
15: '-'
16: '#'
17: '}'
18: '{'
19: '{'
20: '-'
21: ' '
22: '-'
23: '}'
24: '}'
25: '*'
26: '<'
27: '>'
28: '['
29: ']'
30: '('
31: ')'
32: ','
33: '.'
34: '|'
35: '^'
36: '&'
37: '<'
38: '<'
39: '>'
40: '>'
41: '='
42: '>'
43: '/'
44: '+'
45: '-'
46: '|'
47: '|'
48: '<'
49: '>'
50: '!'
51: '='
52: '='
53: '<'
54: '='
55: '>'
56: '='
57: ';'
58: '@'
59: '{'
60: '}'
61: '~'
62: 'e'
63: 'l'
64: 's'
65: 'e'
66: 'i'
67: 'f'
68: 'f'
69: 'o'
70: 'r'
71: 'e'
72: 'n'
73: 'd'
74: 'f'
75: 'o'
76: 'r'
77: 'e'
78: 'l'
79: 'i'
80: 'f'
81: 'e'
82: 'n'
83: 'd'
84: 'i'
85: 'f'
86: 's'
87: 'e'
88: 't'
89: '?'
90: ':'
91: '\'
92: '"'
93: '''
94: '\'
95: '\n'
96: '\r'
97: 'r'
98: 'R'
99: 'r'
100: 'R'
101: 'b'
102: 'B'
103: 'b'
104: 'B'
105: 'r'
106: 'R'
107: 'b'
108: 'B'
109: '"'
110: '''
111: '\n'
112: '\n'
113: '''
114: '"'
115: '*'
116: '*'
117: '/'
118: '/'
119: '*'
120: '*'
121: '{'
122: '{'
123: '-'
124: ' '
125: '/'
126: '*'
127: '*'
128: '/'
129: ' '
130: '-'
131: '}'
132: '}'
133: '{'
134: '#'
135: '-'
136: '-'
137: '#'
138: '}'
139: '.'
140: '_'
141: '`'
142: '.'
143: '.'
144: 'e'
145: 'E'
146: '+'
147: '-'
148: '0'
149: 'x'
150: 'X'
151: ' '
152: '\t'
153: '\r'
154: \u00a0
155: \u2000
156: \u2001
157: \u2003
158: \u2004
159: \u0001-'\t'
160: '\v'-'!'
161: '#'-'&'
162: '('-'['
163: ']'-\u007f
164: \u0080-\ufffc
165: \ufffe-\U0010ffff
166: 'a'-'z'
167: 'A'-'Z'
168: \u0001-'\t'
169: '\v'-\u007f
170: \u0080-\ufffc
171: \ufffe-\U0010ffff
172: '0'-'9'
173: 'a'-'z'
174: 'A'-'Z'
175: \u0001-'\t'
176: '\v'-'['
177: ']'-'_'
178: 'a'-\u007f
179: '0'-'9'
180: 'a'-'f'
181: 'A'-'F'
182: .
*/
